# Generated by Django 5.0.1 on 2024-02-13 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='voting_id',
            new_name='voting',
        ),
    ]
