# Generated by Django 5.0.1 on 2024-03-18 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surApp', '0002_rename_question_id_choice_question_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voting',
            options={},
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(default='checkbox', max_length=50),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='surApp.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surApp.voting'),
        ),
    ]
