# Generated by Django 5.0.1 on 2024-03-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surApp', '0005_vote_delete_uservote'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='is_submit',
            field=models.BooleanField(default=False),
        ),
    ]
